version: "3.8"

services:

    db:
      container_name: postgresql_db_stats
      image: postgres
      restart: always
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}

    pgadmin:
      container_name: pgadmin_stats
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      ports:
        - 5050:80
      depends_on:
        - db

    fastapi:
      container_name: fastapi_stats
      build: .
      command: bash -c "uvicorn statstudio.api.main:api --host 0.0.0.0 --port 8000 --reload"
      volumes:
        - ./statstudio/api:/statstudio/api
      ports:
        - 8000:8000
      restart: always
      depends_on:
        - db

    redis:
      container_name: redis_stat
      image: redis:6.2-alpine

    celery_worker:
      container_name: celery_worker
      build: .
      command: celery -A worker.celery_worker.celery worker --loglevel=info
      volumes:
        - ./worker:/worker
      environment:
        - CELERY_BROKER_URL=${CELERY_BROKER_URL}
        - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      depends_on:
        - fastapi
        - redis

    flower:
      container_name: flower
      build: .
      command: celery -A worker.celery_worker.celery flower --port:5555
      ports:
        - 5556:5555
      environment:
        - CELERY_BROKER_URL=${CELERY_BROKER_URL}
        - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      depends_on:
        - fastapi
        - redis
        - celery_worker